### ISSUE TITLE
The network stack was reset. Pending promises will not be fulfilled. Node-Red crashes.

### ISSUE THREAD

**Issue by LarsSimonsen** [fetchbot/node-red-contrib-ikea-home-smart#25]
My Node-Red crashes in its entirety every few hours. I'm on Windows 10, Node-Red 2.2.0, node-red-contrib-ikea-home-smart 0.3.3. The last console output entry looks like this:
```
1 Feb 07:50:34 - [red] Uncaught Exception:
1 Feb 07:50:34 - [error] Error: The network stack was reset. Pending promises will not be fulfilled.
    at TradfriClient.<anonymous> (C:\Users\***\.node-red\node_modules\node-tradfri-client\build\tradfri-client.js:1011:40)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\***\.node-red\node_modules\node-tradfri-client\build\tradfri-client.js:6:65)
```
I'm puzzled that it brings Node-Red down completely, did't know that a single node had the power to do that.

See also [this issue](https://github.com/AlCalzone/node-tradfri-client/issues/582) in `node-tradfri-client`.

**Comment by osvedman** [comment]
This happens to me as well. It happens randomly when issuing commands to my IKEA blinds from Node-RED.

Node-RED 4.0.9
node-red-contrib-ikea-home-smart 0.3.4

@fetchbot any chance you can look into this?

```
17 Feb 11:38:58 - [red] Uncaught Exception:
17 Feb 11:38:58 - [error] Error: The network stack was reset. Pending promises will not be fulfilled.
    at TradfriClient.<anonymous> (/home/pi/.node-red/node_modules/node-tradfri-client/build/tradfri-client.js:1011:40)
    at Generator.throw (<anonymous>)
    at rejected (/home/pi/.node-red/node_modules/node-tradfri-client/build/tradfri-client.js:6:65)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 7h 16min 55.741s CPU time.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
```
